// Sample data
export const sampleData = [
  {
    id: 1,
    name: 'John Doe',
    age: 30,
    department: 'Engineering',
    salary: 75000,
    joinDate: '2020-01-15',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 28,
    department: 'Marketing',
    salary: 65000,
    joinDate: '2021-03-22',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Bob Johnson',
    age: 35,
    department: 'Engineering',
    salary: 85000,
    joinDate: '2019-07-10',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Alice Brown',
    age: 32,
    department: 'HR',
    salary: 60000,
    joinDate: '2020-11-05',
    status: 'Inactive',
  },
  {
    id: 5,
    name: 'Charlie Wilson',
    age: 29,
    department: 'Engineering',
    salary: 78000,
    joinDate: '2021-01-20',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Diana Davis',
    age: 31,
    department: 'Marketing',
    salary: 70000,
    joinDate: '2020-05-18',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Eve Miller',
    age: 27,
    department: 'Engineering',
    salary: 72000,
    joinDate: '2021-09-12',
    status: 'Active',
  },
  {
    id: 8,
    name: 'Frank Garcia',
    age: 33,
    department: 'HR',
    salary: 58000,
    joinDate: '2019-12-03',
    status: 'Active',
  },
  {
    id: 9,
    name: 'Grace Lee',
    age: 26,
    department: 'Marketing',
    salary: 63000,
    joinDate: '2022-02-14',
    status: 'Active',
  },
  {
    id: 10,
    name: 'Henry Taylor',
    age: 34,
    department: 'Engineering',
    salary: 82000,
    joinDate: '2018-08-25',
    status: 'Inactive',
  },
  {
    id: 11,
    name: 'Ivy Chen',
    age: 25,
    department: 'Marketing',
    salary: 61000,
    joinDate: '2022-06-01',
    status: 'Active',
  },
  {
    id: 12,
    name: 'Jack Anderson',
    age: 36,
    department: 'HR',
    salary: 65000,
    joinDate: '2017-04-12',
    status: 'Active',
  },
  {
    id: 13,
    name: 'Kelly White',
    age: 28,
    department: 'Engineering',
    salary: 76000,
    joinDate: '2020-10-08',
    status: 'Active',
  },
  {
    id: 14,
    name: 'Leo Martinez',
    age: 30,
    department: 'Marketing',
    salary: 68000,
    joinDate: '2019-11-20',
    status: 'Active',
  },
  {
    id: 15,
    name: 'Mia Thompson',
    age: 29,
    department: 'Engineering',
    salary: 79000,
    joinDate: '2021-05-15',
    status: 'Active',
  },
];

// Column configuration
export const columns = [
  {
    field: 'name',
    title: 'Employee Name',
    width: 150,
    type: 'text',
    groupable: true,
  },
  {
    field: 'actions',
    title: 'Actions',
    width: 120,
    type: 'actions',
    sortable: false,
    filterable: false,
    groupable: false,
  },
  {
    field: 'age',
    title: 'Age',
    width: 80,
    type: 'number',
    groupable: true,
  },
  {
    field: 'department',
    title: 'Department',
    width: 120,
    type: 'select',
    groupable: true,
    options: [
      { value: 'Engineering', label: 'Engineering' },
      { value: 'Marketing', label: 'Marketing' },
      { value: 'HR', label: 'HR' },
    ],
  },
  {
    field: 'salary',
    title: 'Salary',
    width: 100,
    type: 'number',
    groupable: true,
    render: (value) => `₹${value?.toLocaleString()}`,
  },
  {
    field: 'joinDate',
    title: 'Join Date',
    width: 120,
    type: 'date',
    groupable: true,
  },
  {
    field: 'status',
    title: 'Status',
    width: 100,
    type: 'select',
    groupable: true,
    options: [
      { value: 'Active', label: 'Active' },
      { value: 'Inactive', label: 'Inactive' },
    ],
    render: (value) => (
      <span className={`status-badge ${value?.toLowerCase()}`}>{value}</span>
    ),
  },
];
