import {
  LayoutDashboard,
  BarChart3,
  Users,
  ShoppingCart,
  Settings,
  Bell,
  MessageSquare,
  CheckSquare,
  User,
  Shield,
  SlidersHorizontal,
  HelpCircle,
  LogOut,
  BookOpen,
  Lock,
  Sliders,
  FileText,
  Phone,
  PieChart,
  TrendingUp,
  Activity,
  FolderKanban,
} from 'lucide-react';

export const mainMenu = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: LayoutDashboard,
    path: '/',
    type: 'menu',
    component: 'Dashboard',
  },
  {
    id: 'analytics',
    title: 'Analytics',
    icon: BarChart3,
    type: 'collapse',
    path: '/analytics',
    component: 'Analytics',
    children: [
      {
        id: 'revenue',
        title: 'Revenue',
        path: '/analytics/revenue',
        icon: PieChart,
        type: 'menu',
        component: 'Revenue',
      },
      {
        id: 'users',
        title: 'User Analytics',
        path: '/analytics/users',
        icon: Users,
        type: 'menu',
        component: 'UserAnalytics',
      },
      {
        id: 'performance',
        title: 'Performance',
        path: '/analytics/performance',
        icon: Activity,
        type: 'menu',
        component: 'Performance',
      },
    ],
  },
  {
    id: 'users',
    title: 'User Management',
    icon: Users,
    type: 'collapse',
    path: '/users',
    component: 'UserManagement',
    children: [
      {
        id: 'user-list',
        title: 'User List',
        path: '/users/list',
        icon: User,
        type: 'menu',
        component: 'UserList',
      },
      {
        id: 'user-roles',
        title: 'Roles & Permissions',
        path: '/users/roles',
        icon: Shield,
        type: 'menu',
        component: 'RolesPermissions',
      },
      {
        id: 'user-activity',
        title: 'User Activity',
        path: '/users/activity',
        icon: Activity,
        type: 'menu',
        component: 'UserActivity',
      },
    ],
  },
  {
    id: 'products',
    title: 'Products',
    icon: ShoppingCart,
    type: 'collapse',
    path: '/products',
    component: 'Products',
    children: [
      {
        id: 'product-list',
        title: 'Product List',
        path: '/products/list',
        icon: FolderKanban,
        type: 'menu',
        component: 'ProductList',
      },
      {
        id: 'product-categories',
        title: 'Categories',
        path: '/products/categories',
        icon: Sliders,
        type: 'menu',
        component: 'Categories',
      },
      {
        id: 'product-inventory',
        title: 'Inventory',
        path: '/products/inventory',
        icon: TrendingUp,
        type: 'menu',
        component: 'Inventory',
      },
    ],
  },
  {
    id: 'settings',
    title: 'Settings',
    icon: Settings,
    type: 'collapse',
    path: '/settings',
    component: 'Settings',
    children: [
      {
        id: 'profile',
        title: 'Profile Settings',
        path: '/settings/profile',
        icon: User,
        type: 'menu',
        component: 'ProfileSettings',
      },
      {
        id: 'security',
        title: 'Security',
        path: '/settings/security',
        icon: Lock,
        type: 'menu',
        component: 'Security',
      },
      {
        id: 'preferences',
        title: 'Preferences',
        path: '/settings/preferences',
        icon: SlidersHorizontal,
        type: 'menu',
        component: 'Preferences',
      },
    ],
  },
  {
    id: 'todo',
    title: 'Todos',
    icon: CheckSquare,
    path: '/todos',
    type: 'menu',
    component: 'Todos',
  },
  {
    id: 'ReactGrid',
    title: 'React Grid',
    icon: CheckSquare,
    path: '/reactgrid',
    type: 'menu',
    component: 'ReactGrid',
  },
  {
    id: 'TestPage',
    title: 'Test Page',
    icon: CheckSquare,
    path: '/testPage',
    type: 'menu',
    component: 'TestPage',
  },
];
export const quickMenu = [
  {
    id: 'notifications',
    title: 'Notifications',
    icon: Bell,
    path: '/notifications',
    badge: {
      content: '5',
      color: 'warning',
    },
  },
  {
    id: 'messages',
    title: 'Messages',
    icon: MessageSquare,
    path: '/messages',
    badge: {
      content: '3',
      color: 'info',
    },
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: CheckSquare,
    path: '/tasks',
    badge: {
      content: '12',
      color: 'error',
    },
  },
];

export const userMenu = [
  {
    id: 'profile',
    title: 'My Profile',
    icon: User,
    path: '/profile',
  },
  {
    id: 'account',
    title: 'Account Settings',
    icon: Settings,
    path: '/account-settings',
  },
  {
    id: 'support',
    title: 'Support',
    icon: HelpCircle,
    path: '/support',
  },
  {
    id: 'logout',
    title: 'Logout',
    icon: LogOut,
    path: '/logout',
  },
];

export const footerMenu = [
  {
    id: 'help',
    title: 'Help Center',
    path: '/help',
    icon: BookOpen,
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    path: '/privacy',
    icon: Lock,
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    path: '/terms',
    icon: FileText,
  },
  {
    id: 'contact',
    title: 'Contact Us',
    path: '/contact',
    icon: Phone,
  },
];
